services:
  whisper-api:
    build: .
    ports:
      - "8090:8000"
    volumes:
      - whisper-cache:/root/.cache/whisper
    environment:
      - DEFAULT_LANGUAGE=
      # - API_KEY_ENABLED=true
    restart: unless-stopped

volumes:
  whisper-cache:
